import { createActions } from '@u';
import types from './types';
import {
  setManageList,
  getManageList,
  getSelectWidgetList
} from './api';

const {
  SET_MANAGE_LIST,
  GET_MANAGE_LIST,
  BATCH_DELECT,
  BATCH_MOVE,
  SELECT_GROUP_ACTIONS,
  SELECT_LIST_ACTIONS,
  ADD_GROUP,
  ADD_DESK,
  DELECT_GROUP,
  RENAME_GROUP,
  MOVE_GROUP,
  STICK_GROUP,
  MOVE_TOP_GROUP,
  MOVE_BOTTOM_GROUP,
  ADD_FOLDER,
  SET_FOLDER_EDIT,
  DELETE_FOLDER,
  RENAME_FOLDER,
  SPLIT_FOLDER,
  ADD_SERVE,
  DELECT_SERVE,
  MOVE_SERVE,
  OPEN_FOLDER,
  CLOSE_FOLDER,
  GET_SELECT_WIDGET_LIST,
  OPEN_BATCH_MOVE,
  CLOSE_BATCH_MOVE,
  SET_EDIT_STATE,
  CANCEL_FOLDER_EDIT,
  SET_CURR_GROUP_INDEX,
  EDIT_TITLE
} = types;

const actions = createActions(
  {
    namespace: 'manage',
  },
  {
    [SET_MANAGE_LIST]: setManageList,
    [GET_MANAGE_LIST]: getManageList,
    [GET_SELECT_WIDGET_LIST]: getSelectWidgetList,
  },
  BATCH_DELECT,
  ADD_GROUP,
  ADD_DESK,
  DELECT_GROUP,
  BATCH_MOVE,
  SELECT_GROUP_ACTIONS,
  SELECT_LIST_ACTIONS,
  RENAME_GROUP,
  MOVE_GROUP,
  STICK_GROUP,
  MOVE_TOP_GROUP,
  MOVE_BOTTOM_GROUP,
  ADD_FOLDER,
  SET_FOLDER_EDIT,
  DELETE_FOLDER,
  RENAME_FOLDER,
  SPLIT_FOLDER,
  ADD_SERVE,
  DELECT_SERVE,
  MOVE_SERVE,
  OPEN_FOLDER,
  CLOSE_FOLDER,
  OPEN_BATCH_MOVE,
  CLOSE_BATCH_MOVE,
  SET_EDIT_STATE,
  CANCEL_FOLDER_EDIT,
  SET_CURR_GROUP_INDEX,
  EDIT_TITLE
);
export default actions;
