import { createTypes } from '@u';

export default createTypes(
  'GET_USER_INFO',
  'GET_WORK_LIST',
  'CHANGE_REQUEST_DISPLAY',
  'CLOSE_REQUEST_DISPLAY',
  'OPEN_FOLDER',
  'CLOSE_FOLDER',
  'SET_CUT_USER',
  'GET_SEARCH_ENTER_LIST',
  'SET_CREATE_ENTER',
  'GET_ENTER_INFO',
  'GET_SEARCH_ENTER_OR_TEAM',
  'GET_APPLICATION_LIST',
);
