import { createActions } from '@u';
import types from './types';
import {
  getServiceList,
  getMessage,
  uploadApplication,
  getPoll,
  getPortal,
  setCurrent,
  getAllEnable,
  getCurrent,
  setCurrentNot,
  getAllEnableNot,
  getCurrentNot,
} from './api';

const {
  REQUEST_START,
  REQUEST_SUCCESS,
  REQUEST_ERROR,
  GET_SERVICE_LIST,
  GET_MESSAGE,
  CHANGE_QUICK_SERVICE_DISPLAY,
  CHANGE_QUICK_SERVICE_HIDDEN,
  POP_MESSAGE,
  CHANGE_MESSAGE_TYPE,
  SHOW_IM,
  HIDE_IM,
  UPLOAD_APPLICATION,
  GET_POLL,
  GET_PORTAL,
  SET_CURRENT,
  GET_ALL_ENABLE,
  GET_CURRENT,
  SET_CURRENT_NOT,
  GET_ALL_ENABLE_NOT,
  GET_CURRENT_NOT,
  SHOW_DIALOG,
  CLOSE_DIALOG_NEW,
  OPEN_FRAME,
  CLOSE_FRAME
} = types;

export default createActions(
  {
    [GET_SERVICE_LIST]: getServiceList,
    [GET_MESSAGE]: getMessage,
    [UPLOAD_APPLICATION]: uploadApplication,
    [GET_POLL]: getPoll,
    [GET_PORTAL]: getPortal,
    [SET_CURRENT]: setCurrent,
    [GET_ALL_ENABLE]: getAllEnable,
    [GET_CURRENT]: getCurrent,
    [SET_CURRENT_NOT]: setCurrentNot,
    [GET_ALL_ENABLE_NOT]: getAllEnableNot,
    [GET_CURRENT_NOT]: getCurrentNot,
  },
  REQUEST_START,
  REQUEST_SUCCESS,
  REQUEST_ERROR,
  CHANGE_QUICK_SERVICE_DISPLAY,
  CHANGE_QUICK_SERVICE_HIDDEN,
  POP_MESSAGE,
  CHANGE_MESSAGE_TYPE,
  SHOW_IM,
  HIDE_IM,
  SHOW_DIALOG,
  CLOSE_DIALOG_NEW,
  OPEN_FRAME,
  CLOSE_FRAME
);
