const texts = {
    placeholder1: "No more than 60 chars",
    radio1: "Prohibited",
    radio2: "Allowed",
    tenantNameLabel: "Enterprise Name",
    tenantNameError: "Please enter enterprise name",
    logoLabel: "",
    logoError: "Please upload picture.",
    logoError2: "It must be a picture.",
    tenantIndustryLabel: "Industry",
    tenantIndustryError: "Please choose an industry",
    tenantSizeLabel: "Staff",
    tenantSizeError: "Please choose scale",
    addressLabel: "",
    addressError: "",
    invitePermissionLabel: "Invitation Rules",
    invitePermissionO1: "Invite All",
    invitePermissionO2: "Invite not Allowed",
    invitePermissionO3: "Invite by Admin",
    joinPermissionLabel: "Allow to Apply",
    joinPermissionO1: "",
    joinPermissionO2: "",
    allowExitLabel: "Users' Quit",
    subordinateTypeLabel: "",
    subordinateTypeO1: "",
    subordinateTypeO2: "",
    isWaterMarkLabel: "Display watermark in contacts",
    infoTitle: "",
    linkmanLabel: "Name",
    linkmanError: "Please enter contact name",
    tenantEmailLabel: "Email",
    tenantEmailError: "",
    tenantEmailPlace: "",
    tenantTelLabel: "Mobile",
    tenantTelError: "Wrong mobile No. format",
    tenantTelPlace: "Please enter mobile number",

    tenantIndustry: [
        { value: "A", label: "Agriculture, Forestry, Animal Husbandry, and Fishery" },
        { value: "B", label: "Mining" },
        { value: "C", label: "Manufacturing" },
        { value: "D", label: "Electricity/Heating Power/Gas/Water Production and Supply" },
        { value: "S", label: "Environment and Public Administration, Social Insurance, and Social Org" },
        { value: "E", label: "Construction" },
        { value: "G", label: "Transportation, Warehousing and Postal Services" },
        { value: "I", label: "Info Transmission, Computer Service and Software" },
        { value: "F", label: "Wholesale and Retail Trade" },
        { value: "H", label: "Accommodation and Catering" },
        { value: "J", label: "Finance and Insurance" },
        { value: "K", label: "Real Estate" },
        { value: "L", label: "Leasing and Business Services" },
        { value: "M", label: "Scientific Research, Technical Services and Geological Prospecting" },
        { value: "N", label: "Water, Environment and Public Facilities Management" },
        { value: "O", label: "Resident Services and Other Services" },
        { value: "P", label: "Education" },
        { value: "Q", label: "Health, Social Security and Social Service" },
        { value: "R", label: "Culture, Sports and Recreation" },
        { value: "T", label: "International Organization" },
    ],
    tenantSizeOption: [
        { value: "A", label: "0-50" },
        { value: "B", label: "51-100" },
        { value: "C", label: "101-200" },
        { value: "D", label: "201-500" },
        { value: "E", label: "501-1000" },
        { value: "F", label: "1001-2000" },
        { value: "G", label: ">2000 people" },
    ]
};

export {
    texts
}
