import { createActions } from 'redux-actions';
import types from './types';

const {
  SET_CONTENT_SRC,
  SET_EXPANDED_SIDEBAR,
  GET_TABS_LIST,
  SET_TABS_CURRENT,
  DEL_TABS,
  GET_PRODUCT_INFO,
  GET_TITLE_SERVICE,
  TITLE_SERVICE_DISPLAY,
  TITLE_SERVICE_HIDDEN,
  PIN_DISPLAY_BLOCK,
  PIN_DISPLAY_NONE,
} = types;

export default createActions(
  {},
  SET_CONTENT_SRC,
  SET_EXPANDED_SIDEBAR,
  GET_TABS_LIST,
  SET_TABS_CURRENT,
  DEL_TABS,
  GET_PRODUCT_INFO,
  GET_TITLE_SERVICE,
  TITLE_SERVICE_DISPLAY,
  TITLE_SERVICE_HIDDEN,
  PIN_DISPLAY_BLOCK,
  PIN_DISPLAY_NONE,
  { namespace: 'work' }
);
