import { createTypes } from '@u';

export default createTypes(
  'SET_MENUS',
  'SET_CURRENT',
  'SET_EXPANDED_SIDEBAR',
  'DEL_TAB',
  'GET_PRODUCT_INFO',
  'GET_TITLE_SERVICE',
  'TITLE_SERVICE_DISPLAY',
  'TITLE_SERVICE_HIDDEN',
  'PIN_DISPLAY_BLOCK',
  'PIN_DISPLAY_NONE',
  'SET_PIN_ADD',
  'SET_ADD_GROUP',
  'GET_PIN_GROUP',
  'SET_PIN_CANCEL'
);
