import { createActions } from '@u';
import types from './types';
import {
  getUserInfo,
  getServiceList,
  uploadApplication,
  getPoll,
  getPortal,
  setCurrent,
  getAllEnable,
  getCurrent,
  setCurrentNot,
  getAllEnableNot,
  getCurrentNot,
  getFolders,
  setFolders,
  addFolders,
} from './api';

const {
  REQUEST_START,
  REQUEST_SUCCESS,
  REQUEST_ERROR,
  GET_USER_INFO,
  SET_USER_INFO,
  GET_SERVICE_LIST,
  CHANGE_QUICK_SERVICE_DISPLAY,
  CHANGE_QUICK_SERVICE_HIDDEN,
  POP_MESSAGE,
  CHANGE_MESSAGE_TYPE,
  SHOW_IM,
  HIDE_IM,
  UPLOAD_APPLICATION,
  GET_POLL,
  GET_PORTAL,
  SET_CURRENT,
  GET_ALL_ENABLE,
  GET_CURRENT,
  SET_CURRENT_NOT,
  GET_ALL_ENABLE_NOT,
  GET_CURRENT_NOT,
  SHOW_DIALOG,
  CLOSE_DIALOG_NEW,
  OPEN_FRAME,
  CLOSE_FRAME,
  OPEN_ROOT,
  ADD_TABS,
  DEL_TABS,
  CLOSE_TABS,
  OPEN_PIN,
  CLOSE_PIN,
  GET_FOLDERS,
  SET_FOLDERS,
  ADD_FOLDERS,
  SET_HAS_WIDGET,
} = types;

export default createActions(
  {
    [GET_SERVICE_LIST]: getServiceList,
    [GET_USER_INFO]: getUserInfo,
    [UPLOAD_APPLICATION]: uploadApplication,
    [GET_POLL]: getPoll,
    [GET_PORTAL]: getPortal,
    [SET_CURRENT]: setCurrent,
    [GET_ALL_ENABLE]: getAllEnable,
    [GET_CURRENT]: getCurrent,
    [SET_CURRENT_NOT]: setCurrentNot,
    [GET_ALL_ENABLE_NOT]: getAllEnableNot,
    [GET_CURRENT_NOT]: getCurrentNot,
    [GET_FOLDERS]: getFolders,
    [SET_FOLDERS]: setFolders,
    [ADD_FOLDERS]: addFolders,
  },
  REQUEST_START,
  REQUEST_SUCCESS,
  REQUEST_ERROR,
  SET_USER_INFO,
  CHANGE_QUICK_SERVICE_DISPLAY,
  CHANGE_QUICK_SERVICE_HIDDEN,
  POP_MESSAGE,
  CHANGE_MESSAGE_TYPE,
  SHOW_IM,
  HIDE_IM,
  SHOW_DIALOG,
  CLOSE_DIALOG_NEW,
  OPEN_FRAME,
  CLOSE_FRAME,
  OPEN_ROOT,
  ADD_TABS,
  DEL_TABS,
  CLOSE_TABS,
  OPEN_PIN,
  CLOSE_PIN,
);
