import { createTypes } from '@u';

export default createTypes(
  'REQUEST_START',
  'REQUEST_SUCCESS',
  'REQUEST_ERROR',
  'GET_PRODUCT_LIST',
  'GET_SERVICE_LIST',
  'GET_MESSAGE',
  'CHANGE_QUICK_SERVICE_DISPLAY',
  'CHANGE_QUICK_SERVICE_HIDDEN',
);
