import { createTypes } from '@u';

export default createTypes(
  'REQUEST_START',
  'REQUEST_SUCCESS',
  'REQUEST_ERROR',
  'GET_SERVICE_LIST',
  'GET_MESSAGE',
  'CHANGE_QUICK_SERVICE_DISPLAY',
  'CHANGE_QUICK_SERVICE_HIDDEN',
  'POP_MESSAGE',
  'GET_LATEST_ACCESS_LIST',
  'GET_PROMOTION_SERVICE_LIST',
  'CHANGE_MESSAGE_TYPE',
  'SHOW_IM',
  'HIDE_IM',
);
