import { createTypes } from '@u';

export default createTypes(
  'SET_CURRENT',
  'SET_EXPANDED_SIDEBAR',
  'DEL_TAB',
  'GET_PRODUCT_INFO',
  'SET_PRODUCT_INFO',
  'GET_TITLE_SERVICE',
  'TITLE_SERVICE_DISPLAY',
  'TITLE_SERVICE_HIDDEN',
  'PIN_DISPLAY_BLOCK',
  'PIN_DISPLAY_NONE',
  'SET_PIN_ADD',
  'SET_ADD_GROUP',
  'GET_PIN_GROUP',
  'SET_PIN_CANCEL',
  'ADD_BRM',
  'POP_BRM',
  'REMOVE_BRM',
  'RETURN_DEFAULT_STATE',
  'SET_TABS',
  'CHANGE_SERVICE',
  'UNSHIFT_TAB',
  'POP_URL',
  'RESET_HISTORY'
);
