const texts = {
    placeholder1: '',
    radio1: '',
    radio2: '',
    tenantNameLabel: '',
    tenantNameError: '',
    logoLabel: '',
    logoError: '',
    logoError2: '',
    tenantIndustryLabel: '',
    tenantIndustryError: '',
    tenantSizeLabel: '',
    tenantSizeError: '',
    addressLabel: '',
    addressError: '',
    invitePermissionLabel: '',
    invitePermissionO1: '',
    invitePermissionO2: '',
    invitePermissionO3: '',
    joinPermissionLabel: '',
    joinPermissionO1: '',
    joinPermissionO2: '',
    allowExitLabel: '',
    subordinateTypeLabel: '',
    subordinateTypeO1: '',
    subordinateTypeO2: '',
    isWaterMarkLabel: '',
    infoTitle: '',
    linkmanLabel: '',
    linkmanError: '',
    tenantEmailLabel: '',
    tenantEmailError: '',
    tenantEmailPlace: '',
    tenantTelLabel: '',
    tenantTelError: '',
    tenantTelPlace: '',

    tenantIndustry: [
        { value: 'A', label: '' },
        { value: 'B', label: '' },
        { value: 'C', label: '' },
        { value: 'D', label: '' },
        { value: 'S', label: '' },
        { value: 'E', label: '' },
        { value: 'G', label: '' },
        { value: 'I', label: '' },
        { value: 'F', label: '' },
        { value: 'H', label: '' },
        { value: 'J', label: '' },
        { value: 'K', label: '' },
        { value: 'L', label: '' },
        { value: 'M', label: '' },
        { value: 'N', label: '' },
        { value: 'O', label: '' },
        { value: 'P', label: '' },
        { value: 'Q', label: '' },
        { value: 'R', label: '' },
        { value: 'T', label: '' },
    ],
    tenantSizeOption: [
        { value: 'A', label: '0-50' },
        { value: 'B', label: '51-100' },
        { value: 'C', label: '101-200' },
        { value: 'D', label: '201-500' },
        { value: 'E', label: '501-1000' },
        { value: 'F', label: '1001' },
        { value: 'G', label: '>2000' },
    ]
};

export {
    texts
}
